### PR TITLE
Repurpose repo to host several plugins

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes https://github.com/spring-cloud/spring-cloud-app-starter-doc-maven-plugin/issues/7

### CODE REVIEW

**Comment by sobychacko** [comment]
By combining multiple plugins in this repository, isn't this making a bit difficult to release them individually.? It could be the case that both the doc and the aggregator plugin have different release cycles. For instance, when we release this aggregator plugin, there is no reason to re-release the doc plugin. If we add more plugins to this repo, then we have to release everything in it if there is a need to fix something in a single plugin. OTOH, it will be too noisy to have individual repos for each plugin.

**Comment by ericbottard** [comment]
One repo doesn't have to mean ONE release.

Note that there is no top-level pom in my PR.

Nor should there be only ONE CI plan.

This is just to combat proliferation of (hard to name, on top of that) repositories polluting the spring-cloud namespace

**Comment by sobychacko** [comment]
The changes are merged.
CI plan here: https://jenkins.spring.io/view/Seeds/job/spring-cloud-app-starter-doc-maven-plugin-spring-cloud-app-starter-metadata-maven-plugin-master-ci/
snapshots are available for both plugins.

**Comment by ericbottard** [comment]
👍

**Pull request merged**
